### PR TITLE
not much

### PR DESCRIPTION
**Pull request by cybernet**
if anything

### CODE REVIEW

**Comment by tianon** [comment]
Interesting -- if this is resolved in all supported releases, we can probably remove the entire "copy-calculation" block this comment is intended for. :sweat_smile:

**Comment by tianon** [comment]
(And if it's only included in some releases, we should be able to adjust the templating to remove the block only for recent enough releases.)

**Comment by pgvishnuram** [comment]
can we fix the uid pointing for alpine dockerfile template 

existing 
RUN addgroup -S -g 1000 redis && adduser -S -G redis -u 999 redis

updated
RUN addgroup -S -g 1000 redis && adduser -S -G redis -u 1000 redis

**Comment by cybernet** [comment]
@tianon are you being ironic ? I just removed a comment 🤣

**Comment by tianon** [comment]
Uh, no?  Do you believe this comment should be removed because the underlying issue it points to is resolved, or was this PR not a serious contribution?

If it's the former, then the block of code which follows this comment (which this comment is in relation to) should no longer be necessary -- if it is still necessary, then we either need to leave the comment or update it.  Either way, to move forward here, we need to verify whether it is no longer necessary and that the upstream fix thus does fix the issue this block of code is resolving (and then remove the block of code, and that change also needs to be made in the templates within this repository or else the image updating bot will revert this change as soon as we merge it).

If it's the latter, then we should close this PR.

**Pull request closed without merging**
