### PR TITLE
Add 32bit variants

### LINKED ISSUE #27: 32 bit?
I was wondering if it would possible to get a 32bit image. I have been trying to get my own built, but I can't seem to get it working. 

I added `libc6-dev-i386` to $buildDeps and removed `--no-install-recommends`. I then changed `make -C /usr/src/redis` to `make 32bit -C /usr/src/redis`. Everything builds fine.

Go to run it. `docker run redis`. Get `exec: "/entrypoint.sh": permission denied`. Add `RUN chmod +x entrypoint.sh`

Now when I try and run it, I get `error: exec failed: no such file or directory`. 

`ls -la /usr/local/bin` gives me:
```
total 8900
drwxrwsr-x  2 root staff    4096 Jul 15 19:02 .
drwxrwsr-x 13 root staff    4096 Jul 15 19:02 ..
-rwxr-xr-x  1 root staff 2141216 Jul 15 19:01 gosu
-rwxr-xr-x  1 root staff 1606733 Jul 15 19:02 redis-benchmark
-rwxr-xr-x  1 root staff   20055 Jul 15 19:02 redis-check-aof
-rwxr-xr-x  1 root staff   44651 Jul 15 19:02 redis-check-dump
-rwxr-xr-x  1 root staff 1711441 Jul 15 19:02 redis-cli
lrwxrwxrwx  1 root staff      12 Jul 15 19:02 redis-sentinel -> redis-server
-rwxr-xr-x  1 root staff 3574515 Jul 15 19:02 redis-server
```

Any idea what's going on? Am I taking the right approach?

Dockerfile: https://gist.github.com/b758f19378c719e3d42e

Entrypoint is the same

### PR DESCRIPTION
**Pull request by tianon**
See also http://redis.io/topics/memory-optimization#using-32-bit-instances

Fixes #27

### CODE REVIEW

**Comment by tianon** [comment]
```diff
diff --git a/3.0/Dockerfile b/3.0/32bit/Dockerfile
index fec8576..890e4ee 100644
--- a/3.0/Dockerfile
+++ b/3.0/32bit/Dockerfile
@@ -6,6 +6,7 @@ RUN groupadd -r redis && useradd -r -g redis redis
 RUN apt-get update && apt-get install -y --no-install-recommends \
 		ca-certificates \
 		curl \
+		libc6-i386 \
 	&& rm -rf /var/lib/apt/lists/*
 
 # grab gosu for easy step-down from root
@@ -21,7 +22,7 @@ ENV REDIS_DOWNLOAD_URL http://download.redis.io/releases/redis-3.0.2.tar.gz
 ENV REDIS_DOWNLOAD_SHA1 a38755fe9a669896f7c5d8cd3ebbf76d59712002
 
 # for redis-sentinel see: http://redis.io/topics/sentinel
-RUN buildDeps='gcc libc6-dev make' \
+RUN buildDeps='gcc gcc-multilib libc6-dev-i386 make' \
 	&& set -x \
 	&& apt-get update && apt-get install -y $buildDeps --no-install-recommends \
 	&& rm -rf /var/lib/apt/lists/* \
@@ -30,7 +31,7 @@ RUN buildDeps='gcc libc6-dev make' \
 	&& echo "$REDIS_DOWNLOAD_SHA1 *redis.tar.gz" | sha1sum -c - \
 	&& tar -xzf redis.tar.gz -C /usr/src/redis --strip-components=1 \
 	&& rm redis.tar.gz \
-	&& make -C /usr/src/redis \
+	&& make -C /usr/src/redis 32bit \
 	&& make -C /usr/src/redis install \
 	&& rm -r /usr/src/redis \
 	&& apt-get purge -y --auto-remove $buildDeps
```

**Comment by tianon** [comment]
```console
$ docker run -it --rm redis:32bit bash
root@ae04dfc7a149:/data# which redis-server
/usr/local/bin/redis-server
root@ae04dfc7a149:/data# ldd /usr/local/bin/redis-server
	linux-gate.so.1 =>  (0xf778c000)
	libm.so.6 => /lib32/libm.so.6 (0xf7738000)
	libdl.so.2 => /lib32/libdl.so.2 (0xf7730000)
	libpthread.so.0 => /lib32/libpthread.so.0 (0xf7710000)
	libc.so.6 => /lib32/libc.so.6 (0xf75a8000)
	/lib/ld-linux.so.2 (0xf7768000)
```

**Comment by tianon** [comment]
Also:
```
                _._                                                  
           _.-``__ ''-._                                             
      _.-``    `.  `_.  ''-._           Redis 3.0.2 (00000000/0) 32 bit
  .-`` .-```.  ```\/    _.,_ ''-._                                   
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 1
  `-._    `-._  `-./  _.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |           http://redis.io        
  `-._    `-._`-.__.-'_.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |                                  
  `-._    `-._`-.__.-'_.-'    _.-'                                   
      `-._    `-.__.-'    _.-'                                       
          `-._        _.-'                                           
              `-.__.-'                                               
```

**Comment by MrMMorris** [comment]
w00t! :smile_cat:

**Comment by yosifkit** [comment]
LGTM

**Pull request merged**
