### PR TITLE
Update to 5.0-rc5

### PR DESCRIPTION
**Pull request by tao12345666333**
And the redis download url has changed. 

> I may start to put betas there as well indeed. Maybe a few I updated in the past... It's better for the users. I'll try to remember to do that starting with the next RC. Thanks.
>
> - @antirez https://twitter.com/antirez/status/1040615962498752517

### CODE REVIEW

**Comment by itamarhaber** [comment]
@tao12345666333 thank you, and good point about the betas.

@tianon please confirm so I'll merge this.

**Comment by tianon** [comment]
If we don't also fix `update.sh`, the bot will revert this in roughly an hour 😅

**Comment by tianon** [comment]
@itamarhaber do you know why https://raw.githubusercontent.com/antirez/redis-hashes/master/README wasn't updated with `-rc5`? (that's what `update.sh` scrapes and why this wasn't picked up automatically)

**Comment by tianon** [comment]
We're good now! :+1:

**Pull request merged**
