### PR TITLE
Add simple Alpine-based variant

### PR DESCRIPTION
**Pull request by tianon**

### CODE REVIEW

**Comment by yosifkit** [comment]
I built this version that uses `gosu` and the duplicate that uses `su-exec` and the size difference is only minor:

```console
$ docker images redis
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
redis               3-alpine-gosu       574ba9032328        12 seconds ago      15.94 MB
redis               3-alpine-su         ccab53ee1294        3 seconds ago       13.52 MB
```

I'd rather stick with the known `gosu`, since it is already prevalent in the official images and has versioned releases for easy upgrade on bugs.

**Comment by ncopa** [comment]
i wrote [su-exec](https://github.com/ncopa/su-exec) because I thought gosu was unnecessarily bloated ;) gosu is bigger than busybox and apk-tools together. I would prefer to use su-exec in the alpine images if possible.

**Comment by tianon** [comment]
I'm not opposed to switching to `su-exec`, but for the official images, consistency is much more important than bloat.  If `su-exec` can be shown to be easily installable in all the cases where `gosu` currently is (pre-compiled static binaries are available for a large number of architectures), and can be shown to be completely feature equivalent (since `gosu` was written in Go specifically to be able to leverage the exact code Docker itself uses for parsing `user:group` strings), then we can evaluate switching.

**Comment by ncopa** [comment]
`su-exec` is completely feature equivalent. It handles all the `user:group`cases mentioned in
https://github.com/opencontainers/runc/blob/master/libcontainer/user/user.go#L230 I did test all the possible cases I could think of and compared with `gosu`.

Not sure how far it make sense to pull this consistency thing. I mean, we don't port `apt-get` to alpine just to be consistent. The `gosu` tool was made because the tools provided on debian systems didn't do what we need it to. Ideally that tool should be upstreamed so you can `apt-get install gosu`. On alpine you can `apk add su-exec` for the exact same functionality.

**Comment by wol4max** [comment]
I agree with @ncopa on this. One of the key goals of Alpine is to reduce bloat. And introducing list specific optimizations is perfectly OK. My vote is to go with su-exec.

**Pull request merged**
