### PR TITLE
Set password for Redis

### PR DESCRIPTION
**Pull request by nguymin4**
If there is an environment variable REDIS_PASSWORD
it will be used as the password for Redis. This is optional.

### CODE REVIEW

**Comment by tianon** [comment]
I like the thought, but with how easy the implementation is, I have to wonder what `docker run -e REDIS_PASSWORD=... redis` offers over just `docker run redis redis-server --requirepass ...`.  Maybe this just needs some documentation?

**Comment by nguymin4** [comment]
Hello, I'm using a PaaS which only provide web interface to create docker container and all configuration should be declared in docker-compose.yml in a text area and in environment variable input box.

Web interface is very limited thus this implementation will help a lot.

**Comment by tianon** [comment]
I just tested the following as it was very successful:
```yaml
db:
  image: redis
  command: redis-server --requirepass some-password-here
```
```console
$ docker-compose up
Recreating temp_db_1...
Attaching to temp_db_1
db_1 |                 _._                                                  
db_1 |            _.-``__ ''-._                                             
db_1 |       _.-``    `.  `_.  ''-._           Redis 3.0.5 (00000000/0) 64 bit
db_1 |   .-`` .-```.  ```\/    _.,_ ''-._                                   
db_1 |  (    '      ,       .-`  | `,    )     Running in standalone mode
db_1 |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
db_1 |  |    `-._   `._    /     _.-'    |     PID: 1
db_1 |   `-._    `-._  `-./  _.-'    _.-'                                   
db_1 |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
db_1 |  |    `-._`-._        _.-'_.-'    |           http://redis.io        
db_1 |   `-._    `-._`-.__.-'_.-'    _.-'                                   
db_1 |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
db_1 |  |    `-._`-._        _.-'_.-'    |                                  
db_1 |   `-._    `-._`-.__.-'_.-'    _.-'                                   
db_1 |       `-._    `-.__.-'    _.-'                                       
db_1 |           `-._        _.-'                                           
db_1 |               `-.__.-'                                               
db_1 | 
db_1 | 1:M 10 Nov 02:21:08.364 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
db_1 | 1:M 10 Nov 02:21:08.365 # Server started, Redis version 3.0.5
db_1 | 1:M 10 Nov 02:21:08.366 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
db_1 | 1:M 10 Nov 02:21:08.366 * The server is now ready to accept connections on port 6379
```

**Comment by nguymin4** [comment]
Oh thank you I see how you do it now. 
I'm new to docker. So it's my bad. I didn't read docs carefully.
Case closed.

**Comment by tianon** [comment]
No worries, glad we got it figured out! :+1:

**Pull request closed without merging**
