### PR TITLE
Update to redis 5.0.3

### PR DESCRIPTION
**Pull request by tao12345666333**
Signed-off-by: Jintao Zhang <zhangjintao9020@gmail.com>

### CODE REVIEW

**Comment by tao12345666333** [comment]
Maybe I am faster than the bot. :rofl:

**Comment by itamarhaber** [comment]
Goddamit - I was beaten by a fellow human being in trying to replace a bot. Is that the kind of world that we're leaving to our children!?!

**Comment by tao12345666333** [comment]
:laughing: Take it easy. Just happened to see Redis released a new version.

Now the bot has updated the version correctly, I will close this.

**Pull request closed without merging**
