### PR TITLE
Server Core support

### PR DESCRIPTION
**Pull request by alexellis**
Testable under image at alexellis2/redis-windows:latest.

Requested by @friism / Michael Friis.

This may derivate slightly from the Linux versions, but could be a useful starting point if not acceptable as-is.

### CODE REVIEW

**Comment by tianon** [comment]
Thanks @alexellis!  This is a great start, and I think that `Get-Content ... | Where ... | Set-Content ...` pattern is really clever! (didn't know `Where` was a thing :innocent:)

I'll probably just carry the PR from here to save you cycles unless you'd rather I leave comments?

**Comment by alexellis** [comment]
Hi @tianon - only just saw this. What did you have in mind?

**Comment by tianon** [comment]
(Sorry for the delay!)

A few things:

- use of `MAINTAINER` is discouraged (and deprecated in 1.13+; https://github.com/docker/docker/pull/25466)
- `SHELL` ought to include `$ErrorActionPreference = 'Stop'`
  - https://github.com/docker-library/golang/blob/4fd5df86eea53623b1009b3621b40a97f9f359e5/1.7/windows/windowsservercore/Dockerfile#L3
  - https://github.com/docker-library/python/blob/1414e3ed653cc9c042fc6184fbd4e9f248746ca1/Dockerfile-windowsservercore.template#L3
  - https://github.com/docker-library/mongo/blob/9729bf2e22760d7d261eed7328f821b1b9d4aece/3.3/windows/windowsservercore/Dockerfile#L3
- re: MSI, does the MSI installing a service cause issues?  the container doesn't auto-start the created service, does it?  also, would the MSI update `PATH` for us automatically, or would we still need to do that manually?
- it'd be handy to have something like `ENV REDIS_VERSION 3.2.100` or `MS_REDIS_VERSION` so it's easier to update in the future (and `-OutFile` might as well skip the version number so we don't have to embed our variable more times or cause more places to update)
- any reason not to install directly to `C:\Redis` since we're in a container?
- does `CMD ["redis-server.exe", "redis.unprotected.conf", "--port", "6379"]` not work?
- the empty `README.md` isn't necessary -- the docs live over in https://github.com/docker-library/docs :+1:

**Comment by alexellis** [comment]
Good feedback. I don't think I have time to work on this so it may be better for you to adapt if you are still interested.

**Comment by tianon** [comment]
I don't love `C:\Program Files\Redis` -- it's got a space in it, which makes bind-mounting/use somewhat more irritating, and we're inside a container, so "polluting" the root of `C:` isn't really a big concern.

In looking at this, I realized we ought to have a `VOLUME` too (similar to the Linux variants for `dump.rdb` from `SAVE`).  I'll keep digging (and see about adding Nano Server and 3.2), and just push to your branch here so we can keep this one PR. :+1:

I think Nano Server variants is a good reason for us to continue consuming the `.zip` files like you're doing here too (so we can keep parity).

**Comment by tianon** [comment]
Ok, I think this is ready for further review now. :smile:

cc @yosifkit

**Pull request merged**
