### PR TITLE
Set user in Dockerfile

### PR DESCRIPTION
**Pull request by J0WI**
This was introduced in https://github.com/docker-library/redis/commit/1d0e9b18d06d8847a6c71e8ee8f05b42089137cc but the memcached image follows a different pattern: https://github.com/docker-library/memcached/tree/2abd5c1e975313238af4291264902812a04a1815

They should be consistent and since I'm not aware of any use case to run this image as arbitrary user I propose to change this one to match the more restrictive behaviour of memcached.

### CODE REVIEW

**Comment by tianon** [comment]
Yeah, the reason this was OK in `memcached` is that `memcached` does not support any sort of saving to disk, whereas `redis` _does_ save to disk, and even does so by default in some situations. :disappointed:

**Comment by J0WI** [comment]
Test need to be updated to do this as root...
https://github.com/docker-library/official-images/blob/master/test/tests/redis-basics-config/run.sh

**Comment by J0WI** [comment]
But even with this change you can run the image with `--user arbitrary` or even `--user root`, can't you?

**Comment by tianon** [comment]
Yes, definitely, but the primary use case for starting as root is a
little bit different -- it's for a user providing a volume that
probably already exists somewhere, but is empty and does *not* have
appropriate permissions (and if we start as root, we can fix them
before we step down).

**Comment by tianon** [comment]
Closing as this is unfortunately working as designed. :heart:

(The constant balance between higher security OOB and usability :sob:)

**Pull request closed without merging**
