### PR TITLE
Update Debain base to stretch (fix #129)

### LINKED ISSUE #129: Consider moving to `stretch` base image
`jessie` is now oldstable.
Should Redis move to use the current stable Debian, `stretch`?

### PR DESCRIPTION
**Pull request by J0WI**
fixes #129

### CODE REVIEW

**Comment by yosifkit** [comment]
Can we add the `gpgconf --kill all` too?

**Comment by J0WI** [comment]
Sure. I planned to do this in a follow-up PR, but I can push it here if you prefer.

**Comment by yosifkit** [comment]
Looks like the 32bit versions need the stretch update too :wink:

**Comment by J0WI** [comment]
Indeed. Would be great to have templates here btw. :laughing:

**Comment by laurieodgers** [comment]
Why was the underlying distro updated from 8 to 9? This has caused breaking changes on our production system

**Comment by tianon** [comment]
Because Jessie is no longer supported by the Debian Security Team, and we
didn't see a lot of breakage potential.

Can you explain more about how you're using Redis that's managed to break
with this update so we can try to reproduce?

**Comment by laurieodgers** [comment]
We're running this in k8s with autoconfiguration of redis.conf in the entrypoint script. The ip of the container was retrieved using `ifconfig eth0 | grep 'inet addr' | awk '{ print $2 }' | cut -d: -f2` which has now been changed to the safer `hostname --ip-address`

ifconfig output in jessie 8:
```
eth0      Link encap:Ethernet  HWaddr 56:4a:18:b4:57:37
          inet addr:10.0.157.62  Bcast:0.0.0.0  Mask:255.255.255.255
          inet6 addr: fe80::544a:18ff:feb4:5737/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:8616981 errors:0 dropped:0 overruns:0 frame:0
          TX packets:6699059 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:761079871 (725.8 MiB)  TX bytes:1291079302 (1.2 GiB)
```

ifconfig output in jessie 9:
```
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.0.2  netmask 255.255.0.0  broadcast 0.0.0.0
        inet6 fe80::42:acff:fe11:2  prefixlen 64  scopeid 0x20<link>
        ether 02:42:ac:11:00:02  txqueuelen 0  (Ethernet)
        RX packets 6  bytes 508 (508.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 6  bytes 508 (508.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

Note the missing `addr` after `inet` in jessie 9. Its a minor change, but a breaking change.

**Comment by laurieodgers** [comment]
The tag we're using is `3.2`. This could be mitigated in future with an appended distro name on the tag? ie `3.2-jessie` `3.2-stretch`?

**Pull request merged**
