### PR TITLE
Updates to Redis v5.0.2

### PR DESCRIPTION
**Pull request by itamarhaber**
Signed-off-by: Itamar Haber <itamar@redislabs.com>

### CODE REVIEW

**Comment by tianon** [comment]
Did the bot not pick this one up?

**Comment by itamarhaber** [comment]
I'm faster than a bot and still got replaced by one... cool.

**Comment by tianon** [comment]
Next time, feel free to merge this sort of bump yourself to beat the bot (especially if you already know it builds successfully). :+1: :heart:

**Comment by itamarhaber** [comment]
🤣

**Pull request closed without merging**
